### PR TITLE
Update loader.php

### PR DESCRIPTION
**Pull request by tutv95**
Fixed function get_path()

### CODE REVIEW

**Comment by rilwis** [comment]
Hi,

Thanks for your contribution.

We actually use `0` to check if the **path begins with themes folder**. Using `false` means not found, which is different and not correct.

Probably you found some bugs, can you please tell me in which scenario it happens?

**Comment by tutv95** [comment]
Hi rilwis,

I'm using meta-box for my plugin and I use extension https://metabox.io/docs/meta-box-conditional-logic/. But it works wrong!

Some static files not found cause URL wrong. For instance:
`http://mysite.dev/wp-content/themes/my-plugin-abc/admin/includes/meta-box-conditional-logic/assets/js/conditional-logic.js`

So I tried to change code just like above and it works.

**Comment by rilwis** [comment]
Thanks for the details. I will check the extension first to see if it's ok to fix. By the way, are you using symlink or simply include the extension inside your theme / plugin?

**Comment by tutv95** [comment]
Yes, I'm using symlink 👍

**Comment by rilwis** [comment]
Probably that's the problem.

Your fix sounds like if the plugin folder:

- is in the plugin folder
- is in the plugin mu folder
- not in the theme folder

which never correct.

While my intend is: if the plugin folder is:

- not in the plugin folder
- not in the plugin mu folder
- in the theme folder

I will check more with that.

**Comment by tutv95** [comment]
In code:
`
$themes_dir = wp_normalize_path( untrailingslashit( dirname( realpath( get_stylesheet_directory() ) ) ) );
`

Why do you need use `realpath()` function?

**Comment by rilwis** [comment]
It's used to resolve the symbolic link and other references like `../`. Does this fail in your case?

**Comment by tutv95** [comment]
Yes. My theme and plugin in the same directory.

**Comment by rilwis** [comment]
Does removing `realpath` work for you?

**Comment by tutv95** [comment]
Yes. If I remove `realpath` $themes_dir look like this: 
`/var/www/my-site.dev/htdocs/wp-content/theme`

And it work fine 👍

**Comment by rilwis** [comment]
Great! Can you modify your pull request so I can accept it?

**Pull request closed without merging**
