### PR TITLE
Added possibility to use your own custom marker

### PR DESCRIPTION
**Pull request by Yerlix**
I needed a custom marker on my map, so I figured out how I could do this easily and with the possibility to distribute this functionality.

I added an extra argument to the google map: marker_settings
This argument is then passed through a series of checks to see if it is correctly filled in.
After the checks, I add the given image url to the map.

### CODE REVIEW

**Comment by spiderPan** [comment]
Do you need to update map-frontend.js file as well?

**Comment by Yerlix** [comment]
I didn't edit the map_frontend.js . I've edited the only the helper file and added my extra code to the meta box declaration.

**Comment by spiderPan** [comment]
I mean you probably need update the map_frontend.js, so that it can reads your icon image url configruation.

**Comment by Yerlix** [comment]
It is possible that you need to update it. 
I've made this change about a year ago and haven't maintained it.

I'm planning on updating this in the future, but for now I haven't the time to do it.

**Comment by funkedgeek** [comment]
Closing this for the time being

**Pull request closed without merging**
