### PR TITLE
Add WPML compatibility

### PR DESCRIPTION
**Pull request by vukvukovich**
* Add WPML compatibility class
(ID translation for post and taxonomy_advanced field types)
* Add get_fields() function for all registered fields retrieval

### CODE REVIEW

**Comment by rilwis** [comment]
Thanks @vukvukovich for your help!

**Comment by dimadin** [comment]
@vukvukovich Is there a reason why is `RWMB_Core::register_meta_boxes()` moved from `admin_init` to `init`? This is not backward compatible. Problem is that any hook for `rwmb_meta_boxes` that is registered after `RWMB_Core::register_meta_boxes()` and before `admin_init` with priority `10` (which in reality means whole `init` and `wp_loaded`) doesn't register boxes anymore.

**Comment by vukvukovich** [comment]
Hm.. yeah, one thing I was afraid of, we had to change it because it was triggering after WPML. I've talked to the author and he said it was safe so I assumed the rest...

**Comment by rilwis** [comment]
@dimadin Somehow WPML requires using `init` action and all meta boxes must be registered **before** that. So I told @vukvukovich to do that.

It's recommended to not wrap the function that register meta boxes to any hook (`init`, `admin_init`, `wp_load`, `plugins_loaded`). If you register meta boxes in plugins/themes, simply hook into `rwmb_meta_boxes` and that should work.

**Comment by dimadin** [comment]
@vukvukovich I don't know how WPML works but requiring that meta boxes must be registered before `init` is wrong, even post types are not registered before that.

@rilwis Where it's recommended, I don't see it in documentation? In any case, this is wrong, plugins shouldn't fire before `plugins_loaded`, this is how many do and so do I, it makes this plugin unusable. Some hierarchy must exist.

**Comment by rilwis** [comment]
@vukvukovich Can you talk to the WPML team to check on the `init` function. I agree with @dimadin that hooking into `init` is too soon.

@dimadin It's not clearly said in the docs. But I added a note that users should not use `admin_init` to register meta boxes, just use `rwmb_meta_boxes` filter.

The plugins doesn't fire **before** `plugins_loaded`. The chain is: `plugins_loadded` (do nothing) > `init` (add hook to register meta boxes and hooks for WPML) > `admin_init` (now not used).

**Comment by dimadin** [comment]
@rilwis You prove my point: if your plugin doesn't fire before `plugins_loaded`, why should other plugins that use `rwmb_meta_boxes` filter? :)

Personally, I was using `wp_loaded`, not `admin_init`, but it doesn't matter, even `init` is to late.

**Comment by rilwis** [comment]
> You prove my point: if your plugin doesn't fire before plugins_loaded, why should other plugins that use rwmb_meta_boxes filter? :)

Not sure what's the problem here. Other plugins can fire at any point they want. Just before the time Meta Box registers meta boxes (which is `init`). Before `init`, there are a lot of room for plugins to load their files and add action `rwmb_meta_boxes`.

**Comment by vukvukovich** [comment]
Exactly @rilwis stated. 

@dimadin Do you have some problematic use case to present?

**Comment by dimadin** [comment]
Here is my situation that triggered problem: custom post type name is defined at `init` (so it's not fixed) and is registered immediately with `register_post_type()`, which means that I don't know name of post type before `init` so I can't register meta box.

If we need to keep this change from this pull request, why can't we enable workaround for people that don't need WPML compatibility? My thinking is that we [save](https://github.com/rilwis/meta-box/blob/64a1f4a02fa9d5730ea6bded8b551792bc690d67/inc/loader.php#L85) instance of `RWMB_Core` class as a property of `RWMB_Loader` and since we can access its instance we can remove action from `init` and add it to later hook? I don't see that nothing is loosed here.

Just recently I [wrote](http://blog.milandinic.com/2016/09/23/make-wordpress-php-class-instances-available-to-developers/) about general problem of not keeping instances available which applies here too.

**Comment by rilwis** [comment]
@dimadin I understand your point. Your blog post is good, too. Would you like to do a PR for that?

@vukvukovich Although `init` works fine for me, but I still prefer `admin_init`. As @dimadin said, if a post type is register at `init`, it might be not available when MB fires these actions.

**Comment by dimadin** [comment]
@rilwis I'll open PR when I do some testing.

**Comment by vukvukovich** [comment]
Guys I've talked with our lead developer and as I assumed already changing this will require a lot of work which would postpone other more urgent work.

We will get there, one day, but he can't tell when.

**Pull request merged**
